name: Parallel
on: push

jobs:
  compose:
    runs-on: ubuntu-22.04

    services:

      mariadb:
        image: bitnami/mariadb:11.2
        env:
          MARIADB_USER: bn_moodle
          MARIADB_PASSWORD: foobar1111
          MARIADB_ROOT_PASSWORD: foobar1111
          MARIADB_DATABASE: bitnami_moodle
        ports:
          - "3306:3306"
        volumes:
          - 'mariadb_data:/bitnami/mariadb'        
        
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Build Moodle Docker Image
      run: |
        docker build -f Dockerfile.moodle -t custom-moodle-image .

    - name: Run Moodle Container
      run: |
        docker run -d --name moodle \
        --env BITNAMI_DEBUG=true \
        --env MOODLE_DATABASE_HOST=mariadb \
        --env MOODLE_DATABASE_PORT_NUMBER=3306 \
        --env MOODLE_DATABASE_USER=bn_moodle \
        --env MOODLE_DATABASE_NAME=bitnami_moodle \
        --env MOODLE_DATABASE_PASSWORD=foobar1111 \
        --env MOODLE_SITE_NAME="Moodle skyvar" \
        --env MOODLE_USERNAME=foobar_user \
        --env MOODLE_PASSWORD=foobar1111 \
        -p 80:8080 -p 443:8443 \
        -v moodledata_data:/bitnami/moodledata \
        -v ./src:/src \
        custom-moodle-image    
          
    - name: Docker cp
      run: docker cp test/config.php moodle:/opt/bitnami/moodle/config.php

    - name: exec 
      run: docker exec moodle php opt/bitnami/moodle/admin/tool/phpunit/cli/init.php

    - name: copy test
      run: docker cp test/feature/. moodle:/opt/bitnami/moodle/local/aiquestions/tests

    - name: test
      run: docker exec moodle bash -c "cd opt/bitnami/moodle && \
                vendor/bin/phpunit local/aiquestions/tests/convert_word_to_pdf_test.php"
